name: Build

on:
- push
- pull_request

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - id: set-matrix
      run: |
        if [ "${{ startsWith(github.ref, 'refs/tags/v') }}" = "true" ]; then
          echo ::set-output name=matrix::{\"include\":[{ \"os\": [\"ubuntu-latest\", \"macos-latest\"]}]}
        else
          echo ::set-output name=matrix::{\"include\":[{ \"os\": [\"ubuntu-latest\"]}]}
        fi

  build:
    strategy:
      fail-fast: true
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.2'
    - name: Install dependencies
      run: |
        go version
        make deps
    - name: Run build
      run: make build
    - name: Run lint
      run: make lint
    - name: Run test
      run: make test
    - name: Rename artifact
      run: |
        mv explain-cloudformation-changeset explain-cloudformation-changeset.$(go env GOOS)-$(go env GOARCH)
    - name: Add artifacts to release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          explain-cloudformation-changeset.*
