name: Build

on:
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.2'
    - name: Install dependencies
      run: |
        go version
        make deps
    - name: Run build
      run: make build
    - name: Run lint
      run: make lint
    - name: Run test
      run: make test
